### ISSUE TITLE
Unsupported mail transport [preview]

### ISSUE THREAD

**Issue by maciej-laskowski** [spatie/laravel-mail-preview#59]
Hi, after upgrading Laravel to 8 (8.10.0) I am getting an error:

In MailManager.php line 172:
Unsupported mail transport [preview].

Any idea what might be wrong? I have tried republishing the config file. I am using the latest laravel-mail-preview 4.0

**Comment by mostafakram** [comment]
I am having the same issue on laravel 7.10 and php 7.4

**Comment by gotroch** [comment]
> I am having the same issue on laravel 7.10 and php 7.4

+1
