### ISSUE TITLE
Ray in controller

### ISSUE THREAD

**Issue by m-bosch** [spatie/laravel-mail-preview#65]
Hi There,

In the following line of code, and the one after that there are calls to the "ray" function, but that function is not available.
[link to code where issue occurs](https://github.com/spatie/laravel-mail-preview/blob/master/src/Http/Controllers/ShowMailController.php#L17)

I just clean installed this package into my project (PHP8/L8) and got the following error:

Error
```
Call to undefined function Spatie\MailPreview\Http\Controllers\ray()
https://standaard-cms-v3.test/spatie-mail-preview?file_type=eml&mail_preview_file_name=969172_subject
```

**Comment by freekmurze** [comment]
Probably you did not install the ray package properly. 

Please open up an issue at spatie/ray mentioning a small app to demonstrate the problem.

**Comment by m-bosch** [comment]
Hi @freekmurze,

sorry if i don't understand correctly, but why should i install the ray app to use Laravel mail preview? It is a dev package according to the composer. Composer didn't install Ray, only when i manually installed ray the project works fine.

imho this package should also work fine without Ray? Or ray should be a dev dependancy.

**Comment by freekmurze** [comment]
I'm confused... It's already a dev dependency: https://github.com/spatie/laravel-mail-preview/blob/7c24bad39919f0c66c3a9310a7db9749545c4eaf/composer.json#L26

So if you require laravel-mail-preview regularly, composer shouldn't pull in the ray package.

**Comment by m-bosch** [comment]
> I'm confused... It's already a dev dependency:
> 
> https://github.com/spatie/laravel-mail-preview/blob/7c24bad39919f0c66c3a9310a7db9749545c4eaf/composer.json#L26
> 
> So if you require laravel-mail-preview regularly, composer shouldn't pull in the ray package.

Indeed, it does not pull ray. But i changed my last line in previous comment. I think Ray SHOULD be a regular dependency instead of `dev`, this because in the code there is a direct link to `Ray` so the function should exists to let the `laravel-mail-preview` package work properly.

**Comment by freekmurze** [comment]
I've removed the stray ray calls and tagged a new version.
