### ISSUE TITLE
Race condition with css inliner

### ISSUE THREAD

**Issue by rudiedirkx** [spatie/laravel-mail-preview#72]
Not sure whose bug it is, maybe `fedeisas/laravel-mail-css-inliner`'s.

css inliner's service provider (in `register()`):

    $this->app->afterResolving('mail.manager', function (MailManager $mailManager) {
        $mailManager->getSwiftMailer()->registerPlugin($this->app->make(CssInlinerPlugin::class));
        return $mailManager;
    });

and mail preview's (in `boot()`):

    $this->app['mail.manager']->extend('preview', function () {
        return new PreviewTransport(
            $this->app->make('Illuminate\Filesystem\Filesystem'),
            $this->app['config']['mailpreview.path'],
            $this->app['config']['mailpreview.maximum_lifetime']
        );
    });

So mail preview is directly accessing (and building) `mail.manager`, which immeditately triggers css inliner's `afterResolving`, which triggers immediately triggers `createTransport()`, with a transport `preview` that doesn't exist yet, because mail preview's `extend()` hasn't even run yet.

Moving mail preview's `extend()` into a `afterResolving('mail.manager', ...)` doesn't help, because when the mail manager is finally created (not on every request, just when sending mail) the same race condition happens.

This wasn't a problem with css inliner 2.2 + `themsaid/laravel-mail-preview`. Maybe because it was a mailer then, not a transport. No idea how to fix this. Typical DI race condition.

**Comment by rudiedirkx** [comment]
> This wasn't a problem with css inliner 2.2 + `themsaid/laravel-mail-preview`. Maybe because it was a mailer then, not a transport. No idea how to fix this. Typical DI race condition.

That was Laravel 6 btw. Different mail config.

**Comment by freekmurze** [comment]
Thanks for reporting. This hasn't bitten me yet and I don't get any reports from other users. That's why I'll probably won't invest time in this for now.

Feel free to PR a fix that works for you.

**Comment by rudiedirkx** [comment]
But I've no idea what a fix would be. You're better at Laravel's DI than I am.

Do you use css inliner + preview without problems? Then I'm doing something wrong.

**Comment by rudiedirkx** [comment]
Can I even PR for 4.x? There's no branch... You don't support fixes for PHP 7.4?

**Comment by freekmurze** [comment]
No, this package is 8.0 only. The old version is somewhere on https://github.com/themsaid

**Comment by rudiedirkx** [comment]
I'm very sure I'm using `spatie/laravel-mail-preview` on PHP 7.4, but maybe that's Composer magic.

PR #73 still good though.
